// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDus9ZQcKNvQkcs7SXq9AYiqWGyiuqMHAU',
    appId: '1:1034937906054:web:2cb38379a5d897c9463207',
    messagingSenderId: '1034937906054',
    projectId: 'session-chat-9bb76',
    authDomain: 'session-chat-9bb76.firebaseapp.com',
    storageBucket: 'session-chat-9bb76.appspot.com',
    measurementId: 'G-MSDS6CEEMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOWHbR7-VUmKlMSTQmOZGcCjweparZhg',
    appId: '1:1034937906054:android:18f9fd7b9e5fbdad463207',
    messagingSenderId: '1034937906054',
    projectId: 'session-chat-9bb76',
    storageBucket: 'session-chat-9bb76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BsP4EB2xPti7BM2AtVOflVsYoOpVV_M',
    appId: '1:1034937906054:ios:99055d3d1d25136f463207',
    messagingSenderId: '1034937906054',
    projectId: 'session-chat-9bb76',
    storageBucket: 'session-chat-9bb76.appspot.com',
    iosBundleId: 'com.example.sessionchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BsP4EB2xPti7BM2AtVOflVsYoOpVV_M',
    appId: '1:1034937906054:ios:99055d3d1d25136f463207',
    messagingSenderId: '1034937906054',
    projectId: 'session-chat-9bb76',
    storageBucket: 'session-chat-9bb76.appspot.com',
    iosBundleId: 'com.example.sessionchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDus9ZQcKNvQkcs7SXq9AYiqWGyiuqMHAU',
    appId: '1:1034937906054:web:870bb0e21f2429af463207',
    messagingSenderId: '1034937906054',
    projectId: 'session-chat-9bb76',
    authDomain: 'session-chat-9bb76.firebaseapp.com',
    storageBucket: 'session-chat-9bb76.appspot.com',
    measurementId: 'G-C651WJL3Q3',
  );
}
